### ISSUE TITLE
Account information not saving to halo2accounts.ini

### ISSUE THREAD

**Issue by Catarax** [PermaNulled/cartographer#80]
Since 2.3, it always expire after a reboot or some days later. Got this on 2 computers.
Really annoying.

H2Launcher as admin only, windows 10 Fall Update

![dzpnd6p3s2q2ew0tnjmhew](https://user-images.githubusercontent.com/3964507/34185783-a0234880-e527-11e7-974a-fd654ba3e8eb.png)

**Comment by KILLER-CHIEF** [comment]
The launcher is no longer in use.

**Comment by Catarax** [comment]
Account is not remembered on v4, always have to Add at startup

**Comment by KILLER-CHIEF** [comment]
Hmm I have an idea to work in your case, please put up with this issue for a few weeks or so until i implement the idea.

**Comment by KILLER-CHIEF** [comment]
Fixed issue. You may need to login just once for it to work permanently and it will also require you to sign in again everywhere if you use a different computer for the first time.

**Comment by Catarax** [comment]
Still having the issue on 4.0.2 with check update done, don't know if it's really out for public.

**Comment by KILLER-CHIEF** [comment]
Oh, this is no longer a Login Token expiring issue. This now comes down to file saving not working for you. Go to %LocalAppData%/Microsoft/Halo 2/ and see if the halo2accounts.ini file exists or not. Also tell me if those 2 folders ('Microsoft' and 'Halo 2' exist or not).
Also keep in mind the default option when adding accounts DOES save it to file. Whatever the button indicates is what will happen when you click it.

**Comment by Catarax** [comment]
Got it to work!

Well, I've understood what goes wrong, when you have the default form, I you toogle "Don't Remember Me" to "Remember Me" displayed, it will not be remembered but "Don't Remember Me" remembers the account.

You have to revert the action.
