### ISSUE TITLE
Some leaves on trees do not render specifically Delta Halo (05a_deltaapproach.map)

### ISSUE THREAD

**Issue by KILLER-CHIEF** [PermaNulled/cartographer#93]
(EDITED). Shader was not ported from H2X to H2PC properly. See below.

**Comment by NukeULater** [comment]
halo2.exe+0x287915
Function that checks for exec flags.

**Comment by KILLER-CHIEF** [comment]
Intro video quality appears to be affected by the WEI Scores returned by PCCompat.dll but no luck in it with the leaves issue.

**Comment by NukeULater** [comment]
might be just your graphics card, on mine they render just fine with your pccompat dll

**Comment by KILLER-CHIEF** [comment]
Yeah, but why tho. and how to fix. that's why i reported that pccompat.dll doesn't affect it.

**Comment by pnill** [comment]
Is this issue still relevant? I've only ever heard of it reported by @KILLER-CHIEF

**Comment by KILLER-CHIEF** [comment]
@PermaNulled Still relevant. Even though now I have a different:
- Install of Windows 7
- Motherboard
- CPU (i5 4th gen)
- 8 to now 14 GB ram
- etc... different peripherals
what stays the same is the drivers and the graphics card which is
![image](https://user-images.githubusercontent.com/3233654/46563769-b49ecd80-c946-11e8-9d44-e391281dae09.png)
Plus one other person has also reported the same problem with NVIDIA tech.

**Comment by Berthalamew** [comment]
Getting the same issue with the trees as well

**Comment by Berthalamew** [comment]
Found out that the leaves only showed up when you switched the shader template on delta halo, but it works fine when the scenery object is remade and placed on a map in Sapien.
(Thanks General for recreating the object).
Map with recreated tree :
https://mega.nz/#!1WxGFCzY!MPSf-EToQl_g8vMQGWgiVTqAr6ukrP7C5T506ySUuJY

**Comment by Keith94** [comment]
The leaves being invisible seems to be specific to Nvidia cards.

A shader override fix was just posted here: https://forums.geforce.com/default/topic/1095882/geforce-drivers/halo-2-pc-has-two-nvidia-specific-issues/post/5974601/#5974601

![nf01khf](https://user-images.githubusercontent.com/5490615/51819001-bf7ac680-2285-11e9-929a-4351dae20ea2.jpg)
![wf89juy](https://user-images.githubusercontent.com/5490615/51819006-c1dd2080-2285-11e9-9b24-56528e4069b8.jpg)

**Comment by General-101** [comment]
You shouldn't be doing DX stuff to fix the shaders. The shader problem is an asset issue.  Berthalamew found out that there was an extra bitmap that didn't exist in H2X and nulling solves the problem.

**Comment by Keith94** [comment]
So, this has been fixed in cartographer? Cool.

**Comment by General-101** [comment]
We have not fixed it yet but the proper way to fix it in my opinion would be to undo the mistake that Hired Gun made when packaging the maps. This means removing the bitmap alpha_white from all tex_bump_alpha_test_single_pass. This bitmap did not exist in the Halo 2 Xbox shaders and is the cause of the problem,

However if you are willing to hear me out we could use someone like you for a different problem. I'm not sure if you've heard but the radar does not work as it should. The fade was broken when Hired Gun brought the game over to PC and this causes the blips to dissapear for a second which if you played H2X then you would know this is not how it is supposed to be. We have a workaround that involves switching the bitmap format but this isn't a true fix. If you are interested please contact us on the Discord for the mod.

**Comment by Keith94** [comment]
Heh. I'm not the developer of the fix; I'm just a messenger.

You should ask @killer-m or post on the GeForce topic I linked above. I'm sure he'd be willing to help you. :)

**Comment by General-101** [comment]
I see. Thank you for pointing me in the right direction then.

**Comment by iSupersniper** [comment]
Is this currently fixed right now? @General-101

**Comment by General-101** [comment]
There is test code to fix a single shader in a specific level. I wanted to come up with code that could go through the shaders and search for a specific shader template datum. Then go to a certain offset and null the 4th index in bitmap I think it was. Was too complicated for me to actually put into action tho.

**Comment by xxmart1naxx** [comment]
For your information, 05b_deltatowers is affected by this issue aswell.

**Comment by Berthalamew** [comment]
Yea this issue affects a bunch of other maps as well like the vines on Ivory Tower

**Comment by xxmart1naxx** [comment]
I suggest we look at all the maps and identify every single one affected.

**Comment by num0005** [comment]
Fixed in 91a520121a2c67b047c6ac8a5771a431d2a040d4 other Nvidia related bugs are fixed by #236

**Comment by xxmart1naxx** [comment]
This should be closed then, shouldn't it?

**Comment by num0005** [comment]
Yes

**Comment by nukeulater** [comment]
Consider closing the issue.

**Comment by Keith94** [comment]
This was also fixed in the [MCC patch](https://support.halowaypoint.com/hc/en-us/articles/360042882732-Halo-The-Master-Chief-Collection-Patch-Notes-5-12-20) released today.

>Leaves now render appropriately when using NVIDIA hardware

**Comment by demonsako** [comment]
> 
> 
> This was also fixed in the [MCC patch](https://support.halowaypoint.com/hc/en-us/articles/360042882732-Halo-The-Master-Chief-Collection-Patch-Notes-5-12-20) released today.
> 
> > Leaves now render appropriately when using NVIDIA hardware

I'm gonna be the first to say it but stop sending messages here fuckin tool
